const TYPES = {
  SET_TODO_LIST: 'SET_TODO_LIST',
  SET_FILTER: 'SET_FILTER',
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
  TOGGLE_ALL: 'TOGGLE_ALL',
};

export default TYPES;
